<a href="https://colab.research.google.com/github/Sai0210/coursera-test/blob/main/Home%20Assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

# Create a random tensor of shape (4, 6)
tensor = tf.random.uniform((4, 6))
print("Original Tensor:\n", tensor)

# Find its rank and shape
rank = tf.rank(tensor)
shape = tf.shape(tensor)
print(f"Original Tensor Rank: {rank.numpy()}")
print(f"Original Tensor Shape: {shape.numpy()}")

Original Tensor:
 tf.Tensor(
[[0.7182822  0.9493952  0.4234841  0.6592581  0.89030755 0.39735246]
 [0.681473   0.42173934 0.93383455 0.54819477 0.61187434 0.22419024]
 [0.25465405 0.6130252  0.24769938 0.22671771 0.36988854 0.966812  ]
 [0.4246322  0.52510023 0.36550224 0.14199209 0.0083245  0.35588038]], shape=(4, 6), dtype=float32)
Original Tensor Rank: 2
Original Tensor Shape: [4 6]


In [5]:
# Reshape it into (2, 3, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
print("Reshaped Tensor:\n", reshaped_tensor)

Reshaped Tensor:
 tf.Tensor(
[[[0.7182822  0.9493952  0.4234841  0.6592581 ]
  [0.89030755 0.39735246 0.681473   0.42173934]
  [0.93383455 0.54819477 0.61187434 0.22419024]]

 [[0.25465405 0.6130252  0.24769938 0.22671771]
  [0.36988854 0.966812   0.4246322  0.52510023]
  [0.36550224 0.14199209 0.0083245  0.35588038]]], shape=(2, 3, 4), dtype=float32)


In [6]:
# Transpose it to (3, 2, 4)
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print("Transposed Tensor:\n", transposed_tensor)

Transposed Tensor:
 tf.Tensor(
[[[0.7182822  0.9493952  0.4234841  0.6592581 ]
  [0.25465405 0.6130252  0.24769938 0.22671771]]

 [[0.89030755 0.39735246 0.681473   0.42173934]
  [0.36988854 0.966812   0.4246322  0.52510023]]

 [[0.93383455 0.54819477 0.61187434 0.22419024]
  [0.36550224 0.14199209 0.0083245  0.35588038]]], shape=(3, 2, 4), dtype=float32)


In [7]:
# Broadcast a smaller tensor (1, 4) to match the larger tensor and add them
small_tensor = tf.random.uniform((1, 4))
broadcasted_tensor = tf.broadcast_to(small_tensor, (3, 2, 4))
print("Broadcasted Small Tensor:\n", broadcasted_tensor)

Broadcasted Small Tensor:
 tf.Tensor(
[[[0.20846748 0.79901206 0.5741701  0.15803778]
  [0.20846748 0.79901206 0.5741701  0.15803778]]

 [[0.20846748 0.79901206 0.5741701  0.15803778]
  [0.20846748 0.79901206 0.5741701  0.15803778]]

 [[0.20846748 0.79901206 0.5741701  0.15803778]
  [0.20846748 0.79901206 0.5741701  0.15803778]]], shape=(3, 2, 4), dtype=float32)


In [8]:
# Add the broadcasted tensor to the transposed tensor
result_tensor = transposed_tensor + broadcasted_tensor
print("Resulting Tensor after Addition:\n", result_tensor)

Resulting Tensor after Addition:
 tf.Tensor(
[[[0.9267497  1.7484072  0.9976542  0.8172959 ]
  [0.46312153 1.4120373  0.8218695  0.3847555 ]]

 [[1.098775   1.1963645  1.2556431  0.5797771 ]
  [0.578356   1.7658241  0.9988023  0.683138  ]]

 [[1.142302   1.3472068  1.1860445  0.38222802]
  [0.5739697  0.94100416 0.5824946  0.51391816]]], shape=(3, 2, 4), dtype=float32)
